apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ian-cluster
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/apps
    repoURL: 'git@github.com:smileostrich/custom-cluster.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
